[workspace]
resolver = "2"

members = [
	"gem-flasher",
	"gem-imager-cli",
	"gem-imager-gui",
	"gem-flasher-sd",
	"gem-downloader",
	"gem-config",
	"gem-helper",
	"gem-flasher-dfu",
	"gem-drivelist",
	"gem-iced-widgets",
	"gem-i18n",
	"gem-winusb",
	"gem-winusb-helper"
]

[profile.release]
lto = true
codegen-units = 1

[workspace.package]
version = "0.9.0"
edition = "2024"
authors = ["T3 Gemstone Devteam <dev@t3gemstone.org>"]
repository = "https://github.com/Toxpox/gem-imager-rs"
license = "MIT"
