name = "gem-imager-gui"
product-name = "T3 Gemstone Imager"
identifier = "org.t3gemstone.imager"
version = "0.9.0"
authors = ["T3 Gemstone Devteam <dev@t3gemstone.org>"]
publisher = "T3 Gemstone"
description = "Install operating system images for T3 Gemstone boards."
category = "DeveloperTool"
target-triple = "x86_64-pc-windows-msvc"
out-dir = "gem-imager-gui/dist"
binaries-dir = "target/x86_64-pc-windows-msvc/release"
icons = ["gem-imager-gui/assets/icons/icon.*"]

[[binaries]]
path = "gem-imager-gui"
main = true

[[resources]]
src = "target/x86_64-pc-windows-msvc/release/gem-winusb-helper.exe"
target = "gem-winusb-helper.exe"

[[resources]]
src = "gem-winusb/native/x86_64-pc-windows-msvc/libwdi.dll"
target = "libwdi.dll"

[[resources]]
src = "gem-winusb/third_party/libwdi/COPYING-LGPL"
target = "licenses/libwdi/COPYING-LGPL"

[[resources]]
src = "gem-winusb/third_party/libwdi/Microsoft-WDF-License.rtf"
target = "licenses/libwdi/Microsoft-WDF-License.rtf"

[wix]
banner-path = "gem-imager-gui/assets/icons/installer_banner.png"
dialog-image-path = "gem-imager-gui/assets/icons/dialog_image.png"
