//! The three key derivations `gem-first-boot` expects, and nothing else.
//!
//! Each one has a published test vector, and each vector is checked in this module's tests. None of
//! these functions accepts or returns a plain `String` for a secret — inputs are [`Secret`] and
//! outputs are [`DerivedSecret`], which zeroes itself on drop.

use cipher::{BlockEncrypt, KeyInit, generic_array::GenericArray};
use hmac::Hmac;
use sha_crypt::Sha512Params;
use sha1::Sha1;

use super::secret::{DerivedSecret, Secret};
use super::{T3GemInitError, WPA_PSK_HEX_LEN};

/// crypt(3) salt length in characters. The SHA-crypt specification caps it at 16.
const CRYPT_SALT_LEN: usize = 16;

/// The crypt(3) base64 alphabet.
///
/// Exactly 64 symbols, so 6 random bits map to one character with **no rejection sampling and no
/// modulo bias** — the salt is a uniform draw straight from the OS CSPRNG.
const CRYPT_SALT_ALPHABET: &[u8; 64] =
    b"./0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";

/// WPA-PSK is defined as PBKDF2-HMAC-SHA1 with exactly this iteration count (IEEE 802.11i).
const WPA_PBKDF2_ITERATIONS: u32 = 4096;

/// Hash an account password as SHA-512 crypt (`$6$`), the form `gem-first-boot` feeds to `chpasswd`.
///
/// The salt comes from [`getrandom`], i.e. the operating system CSPRNG. `gem-imager` seeds a
/// Mersenne Twister for this; that is not a CSPRNG and is deliberately not reproduced.
pub(super) fn sha512_crypt_os_salt(password: &Secret) -> Result<DerivedSecret, T3GemInitError> {
    let salt = random_crypt_salt()?;
    sha512_crypt_with_salt(password, &salt)
}

/// The deterministic half of [`sha512_crypt_os_salt`], so the algorithm can be pinned to a test
/// vector. Randomised output cannot be compared byte-for-byte, which is why the salt is a parameter
/// here and generated by the caller in production.
fn sha512_crypt_with_salt(password: &Secret, salt: &str) -> Result<DerivedSecret, T3GemInitError> {
    // 5000 rounds is the crypt(3) default, and the default is what is omitted from the `$6$` prefix.
    let params =
        Sha512Params::new(sha_crypt::ROUNDS_DEFAULT).map_err(|_| T3GemInitError::PasswordHash)?;
    let hash = sha_crypt::sha512_crypt_b64(password.expose().as_bytes(), salt.as_bytes(), &params)
        .map_err(|_| T3GemInitError::PasswordHash)?;

    Ok(DerivedSecret::new(format!("$6${salt}${hash}")))
}

fn random_crypt_salt() -> Result<String, T3GemInitError> {
    let mut bytes = [0u8; CRYPT_SALT_LEN];
    getrandom::fill(&mut bytes).map_err(|_| T3GemInitError::Csprng)?;

    Ok(bytes
        .iter()
        .map(|b| CRYPT_SALT_ALPHABET[usize::from(b & 0x3f)] as char)
        .collect())
}

/// Derive the 256-bit WPA PSK from an SSID and passphrase, rendered as 64 lowercase hex digits.
///
/// The passphrase never reaches the card: `gem-first-boot` writes `wifipasswd` straight into a
/// NetworkManager profile, and a PSK there is as usable as the passphrase while not being the
/// string the user may have reused elsewhere.
pub(super) fn wpa_psk(ssid: &str, passphrase: &Secret) -> Result<DerivedSecret, T3GemInitError> {
    let mut psk = [0u8; 32];
    pbkdf2::pbkdf2::<Hmac<Sha1>>(
        passphrase.expose().as_bytes(),
        ssid.as_bytes(),
        WPA_PBKDF2_ITERATIONS,
        &mut psk,
    )
    .map_err(|_| T3GemInitError::PasswordHash)?;

    Ok(DerivedSecret::new(const_hex::encode(psk)))
}

/// Validate a passphrase the user supplied as a ready-made 64-hex-digit PSK.
///
/// Accepting it verbatim is required (the secret-handling policy) — re-running PBKDF2 over a PSK would
/// silently produce a key that does not match the network.
pub(super) fn normalize_psk_hex(value: &Secret) -> Result<DerivedSecret, T3GemInitError> {
    let raw = value.expose();
    if raw.len() != WPA_PSK_HEX_LEN || !raw.bytes().all(|b| b.is_ascii_hexdigit()) {
        return Err(T3GemInitError::WifiPassphraseLength);
    }

    Ok(DerivedSecret::new(raw.to_ascii_lowercase()))
}

/// Encrypt a VNC password the way the classic `vncpasswd` tool does.
///
/// Single-block DES with a hard-coded key, and each key byte bit-reversed because the original
/// implementation fed the key in LSB-first. This is obfuscation, not security — it is reproduced
/// only because it is the format the VNC server on the image reads. The caller enforces the 8-byte
/// limit; this function pads with zeros and never truncates.
pub(super) fn vnc_obfuscate(password: &Secret) -> Result<DerivedSecret, T3GemInitError> {
    const VNC_FIXED_KEY: [u8; 8] = [0x17, 0x52, 0x6b, 0x06, 0x23, 0x4e, 0x58, 0x07];

    let plain = password.expose().as_bytes();
    if plain.len() > super::VNC_PASSWORD_MAX_LEN {
        return Err(T3GemInitError::VncPasswordTooLong { len: plain.len() });
    }

    let mut block = [0u8; 8];
    block[..plain.len()].copy_from_slice(plain);

    let key: [u8; 8] = VNC_FIXED_KEY.map(u8::reverse_bits);
    let cipher = des::Des::new(&GenericArray::from(key));
    let mut block = GenericArray::from(block);
    cipher.encrypt_block(&mut block);

    Ok(DerivedSecret::new(const_hex::encode(block)))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// the customization test contract: a fixed salt pins the algorithm, and an independent verifier
    /// (`sha512_check`, which re-derives from the emitted salt) confirms the string is a real
    /// crypt(3) hash rather than a lookalike.
    #[test]
    fn sha512_crypt_matches_the_reference_vector() {
        // Vector from Ulrich Drepper's SHA-crypt specification.
        let hash = sha512_crypt_with_salt(&Secret::new("Hello world!"), "saltstring").unwrap();
        assert_eq!(
            *hash,
            "$6$saltstring$svn8UoSVapNtMuq1ukKS4tPQd8iKwSMHWjl/O817G3uBnIFNjnQJuesI68u4OTLiBFdcbYEdFCoEOfaS35inz1"
        );

        sha_crypt::sha512_check("Hello world!", &hash).expect("independent verify");
        sha_crypt::sha512_check("Hello world", &hash).expect_err("wrong password must not verify");
    }

    #[test]
    fn sha512_crypt_salt_comes_from_the_os_csprng_and_is_never_reused() {
        let a = sha512_crypt_os_salt(&Secret::new("gemstone")).unwrap();
        let b = sha512_crypt_os_salt(&Secret::new("gemstone")).unwrap();

        assert!(a.starts_with("$6$"));
        // Same password, different salt: a byte-for-byte comparison of two runs is therefore not a
        // valid test, which is why the vector above fixes the salt instead.
        assert_ne!(*a, *b);
        sha_crypt::sha512_check("gemstone", &a).expect("verifies against its own salt");

        let salt = &a["$6$".len()..a.len() - 86 - 1];
        assert_eq!(salt.len(), CRYPT_SALT_LEN);
        assert!(salt.bytes().all(|b| CRYPT_SALT_ALPHABET.contains(&b)));
    }

    /// The official WPA test vectors from IEEE 802.11i Annex H.4.
    #[test]
    fn wpa_psk_matches_the_official_vectors() {
        for (passphrase, ssid, expected) in [
            (
                "password",
                "IEEE",
                "f42c6fc52df0ebef9ebb4b90b38a5f902e83fe1b135a70e23aed762e9710a12e",
            ),
            (
                "ThisIsAPassword",
                "ThisIsASSID",
                "0dc0d6eb90555ed6419756b9a15ec3e3209b63df707dd508d14581f8982721af",
            ),
            (
                "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
                "ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ",
                "4fd16ee24bd1d8f9e7ebd86cbd802d0b3acfd23cb08de414da4e1690e474b857",
            ),
        ] {
            let psk = wpa_psk(ssid, &Secret::new(passphrase)).unwrap();
            assert_eq!(*psk, expected);
        }
    }

    /// A Turkish SSID is a normal input; PBKDF2 salts with the raw UTF-8 bytes, so this must not
    /// panic or mangle the SSID.
    #[test]
    fn wpa_psk_handles_a_unicode_ssid() {
        let psk = wpa_psk("Ağ-Çekirdek", &Secret::new("parola1234")).unwrap();
        assert_eq!(psk.len(), WPA_PSK_HEX_LEN);
        assert!(psk.bytes().all(|b| b.is_ascii_hexdigit()));
    }

    #[test]
    fn a_64_hex_psk_is_accepted_verbatim_and_anything_else_is_rejected() {
        let psk = "0DC0D6EB90555ED6419756B9A15EC3E3209B63DF707DD508D14581F8982721AF";
        assert_eq!(
            *normalize_psk_hex(&Secret::new(psk)).unwrap(),
            psk.to_ascii_lowercase()
        );

        // 63 hex digits, 1 digit, 65 hex digits, and 64 characters that are not all hex.
        let too_long = format!("{psk}0");
        let not_hex = "z".repeat(64);
        for bad in [&psk[..63], "0", too_long.as_str(), not_hex.as_str()] {
            assert!(normalize_psk_hex(&Secret::new(bad)).is_err());
        }
    }

    /// The `vncpasswd` vector the board has to accept.
    ///
    /// Both halves of the algorithm are pinned independently, because "it matches what our own code
    /// produces" would not be a test at all:
    ///
    /// * The DES primitive is anchored by the NIST all-zeros known-answer test below, so the cipher
    ///   is standard DES and not a lookalike.
    /// * The expected value was cross-checked against a textbook DES implementation outside this
    ///   crate, driven with the same bit-reversed fixed key `gem-imager` uses
    ///   (`imagewriter.cpp:1518`, over the standard tables in `src/dependencies/crypt/des.cpp`).
    ///
    /// It has **not** been confirmed against a running VNC server on real hardware; that belongs to
    /// the hardware acceptance matrix.
    #[test]
    fn vnc_obfuscation_matches_the_cross_checked_vector() {
        assert_eq!(
            *vnc_obfuscate(&Secret::new("1234")).unwrap(),
            "ee5b0e48c8fe9771"
        );
        assert_eq!(
            *vnc_obfuscate(&Secret::new("gemstone")).unwrap(),
            "269936771b41d928"
        );
        // Shorter than 8 bytes is zero-padded, so an explicitly padded password is the same value.
        assert_eq!(
            *vnc_obfuscate(&Secret::new("1234\0\0\0\0")).unwrap(),
            "ee5b0e48c8fe9771"
        );
    }

    /// FIPS 46-3 known-answer test: DES with an all-zero key and an all-zero block.
    ///
    /// Without this, the vector above only proves this crate agrees with itself.
    #[test]
    fn the_des_primitive_is_standard_des() {
        use cipher::generic_array::GenericArray;

        let cipher = des::Des::new(&GenericArray::from([0u8; 8]));
        let mut block = GenericArray::from([0u8; 8]);
        cipher.encrypt_block(&mut block);

        assert_eq!(const_hex::encode(block), "8ca64de9c1b123a7");
    }

    /// the secret-handling policy: no silent truncation. A 9-byte password is an error, not 8 bytes of
    /// it, because the user would otherwise be told a password that does not open the session.
    #[test]
    fn vnc_password_over_eight_bytes_is_rejected_not_truncated() {
        assert!(matches!(
            vnc_obfuscate(&Secret::new("123456789")),
            Err(T3GemInitError::VncPasswordTooLong { len: 9 })
        ));
        // The limit is in bytes, not characters: four 2-byte characters are fine, five are not.
        assert!(vnc_obfuscate(&Secret::new("çççç")).is_ok());
        assert!(vnc_obfuscate(&Secret::new("ççççç")).is_err());
    }
}
