[package]
name = "gem-winusb-helper"
description = "Consoleless elevated WinUSB provisioning helper for T3 Gemstone Imager."
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "gem-winusb-helper"
path = "src/main.rs"
test = false
bench = false

[dependencies]
gem-winusb = { path = "../gem-winusb" }

[build-dependencies]
embed-resource = "3.0"
